from __future__ import annotations

from typing import Any, Protocol


class SteamProvider(Protocol):
    async def get_owned_games(self, steam_id: str, force: bool = False) -> dict[str, Any]: ...
    async def get_recent_games(self, steam_id: str, count: int = 0) -> dict[str, Any]: ...
    async def get_player_summary(self, steam_id: str) -> dict[str, Any]: ...
    async def get_steam_level(self, steam_id: str) -> int | None: ...
    async def get_current_players(self, appid: int) -> dict[str, Any]: ...
    async def get_game_achievements(self, steam_id: str, appid: int, language: str = "english") -> dict[str, Any]: ...
    async def get_wishlist(self, steam_id: str, force: bool = False) -> dict[str, Any]: ...
    async def get_friend_list(self, steam_id: str) -> list[dict[str, Any]]: ...
    async def get_owned_games(self, steam_id: str, force: bool = False) -> dict[str, Any]: ...
    async def get_player_summaries(self, steam_ids: list[str]) -> list[dict[str, Any]]: ...


class LocalSteamProvider:
    """Reserved boundary for an opt-in Windows sidecar; a VPS has no local Steam files."""

    @staticmethod
    def capabilities() -> dict[str, object]:
        return {
            "available": False,
            "provider": "local_steam_sidecar",
            "reason": "not_connected",
            "capabilities": ["installed_state", "disk_usage", "download_queue", "local_saves"],
        }
